Feature/places
VasylDolishnii/goit-MainMasters pull request #7
Opened 2023-01-26 19:18 UTC by VasylDolishnii

2023-01-27 13:44 UTC, KJachimstal commented
Resolve conflicts. File main.css.map shouldt be changed. Rest its ok.

2023-01-29 09:54 UTC, KJachimstal requested changes
First of all You can remove the 34th line in index.html is just for presentation purposes. Second thing you need to correct is typo in "src/sass/untils/_vars.css".

2023-01-29 09:54 UTC, KJachimstal commented on src/index.html
> +      <!-- <include src="./partials/buttons.html"></include> -->
You can remove the 34th line in index.html is just for presentation purposes.

2023-01-31 20:30 UTC, matilis approved these changes

2023-01-31 20:52 UTC, KJachimstal approved these changes

2023-01-31 20:52 UTC, matilis approved these changes

2023-01-31 20:52 UTC, matilis approved these changes

2023-01-31 20:52 UTC, matilis approved these changes

2023-01-31 20:53 UTC, matilis approved these changes

2023-01-31 20:53 UTC, KamilaDudzik approved these changes

2023-01-31 20:53 UTC, merged